//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.23 at 08:57:26 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.kimthanh.com/schema/product", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package sample.jaxb.product;
